name := "SparkMe Project"
version := "1.0"
organization := "edureka"
scalaVersion := "2.11.8"
val sparkVersion = "2.1.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % sparkVersion%"provided"
libraryDependencies += "org.apache.spark" %% "spark-sql" % sparkVersion %"provided"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging" % "3.9.0"
resolvers += Resolver.mavenLocal